# Generated by Django 3.1.5 on 2021-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
