# Generated by Django 3.1.5 on 2021-01-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_joined',
            new_name='date',
        ),
    ]
